server:
   port: 9000
   netty:
      connection-timeout: 10s
      idle-timeout: 15s
   shutdown: graceful
spring:
   application:
      name: edge-service
   lifecycle:
      timeout-per-shutdown-phase: 15s
   cloud:
      gateway:
         httpclient:
            connect-timeout: 15000
            response-timeout: 15s
            pool:
               type: elastic
               max-idle-time: 15s
               max-life-time: 60s

         routes:
         -  id: catalog-route
            uri: ${CATALOG_SERVICE_URL:http://localhost:9001}/books
            predicates:
            - Path=/books/**
            filters:
            -  name: CircuitBreaker
               args:
                  name: catalogCircuitBreaker
                  fallbackUri: forward:/catalog-fallback
                  statusCodes:
                  - NOT_FOUND
                  - INTERNAL_SERVER_ERROR
            -  name: Retry
               args:
                  retries: 3
                  methods: GET
                  series: SERVER_ERROR
                  exceptions: java.net.ConnectException
                  backoff:
                     firstBackoff: 5s
                     maxBackOff: 90s
                     factor: 2
                     basedOnPreviousValue: false
         -  id: order-route
            uri: ${ORDER_SERVICE_URL:http://localhost:9002}/orders
            predicates:
            - Path=/orders/**
            filters:
            -  name: CircuitBreaker
               args:
                  name: orderCircuitBreaker
                  statusCodes:
                  - NOT_FOUND
                  - INTERNAL_SERVER_ERROR
            -  name: Retry
               args:
                  retries: 3
                  methods: GET
                  series: SERVER_ERROR
                  exceptions: java.net.ConnectException
                  backoff:
                     firstBackoff: 1s
                     maxBackOff: 10s
                     factor: 2
                     basedOnPreviousValue: false

resilience4j:
   circuitbreaker:
      configs:
         default:
            slidingWindowSize: 10
            permittedNumberOfCallsInHalfOpenState: 2
            failureRateThreshold: 50
            waitDurationInOpenState: 15000
            recordExceptions: java.net.ConnectException
            recordFailurePredicate: com.polarbook.edgeservice.RecordFailurePredicate
   timelimiter:
      configs:
         default:
            timeoutDuration: 60s

logging:
    pattern:
      level: "%5p [${spring.application.name},%X{trace_id},%X{span_id}]"
    group:
      circuitbreaker: io.github.resilience4, org.springframework.cloud.circuitbreaker
    level:
      circuitbreaker: DEBUG
      io.reactor.netty: DEBUG
      org.springframework.cloud.gateway: DEBUG

management:
   endpoints:
      web:
         exposure:
            include: '*'
   endpoint:
      health:
         show-details: always
         show-components: always
         probes:
            enabled: true
   info:
      env:
         enabled: true
      java:
         enabled: true
      os:
         enabled: true
   metrics:
      tags:
         application: ${spring.application.name}