spring:
   application:
      name: edge-service
   lifecycle:
      timeout-per-shutdown-phase: 15s
   cloud:
      gateway:
         httpclient:
            connect-timeout: 15000
            response-timeout: 15s
            pool:
               type: elastic
               max-idle-time: 15s
               max-life-time: 60s

         routes:
         -  id: catalog-route
            uri: http://catalog-service:80/books
            predicates:
            - Path=/books/**
            filters:
            -  name: CircuitBreaker
               args:
                  name: catalogCircuitBreaker
                  fallbackUri: forward:/catalog-fallback
                  statusCodes:
                  - NOT_FOUND
                  - INTERNAL_SERVER_ERROR
            -  name: Retry
               args:
                  retries: 3
                  methods: GET
                  series: SERVER_ERROR
                  exceptions: java.net.ConnectException
                  backoff:
                     firstBackoff: 5s
                     maxBackOff: 90s
                     factor: 2
                     basedOnPreviousValue: false
         -  id: order-route
            uri: http://order-service:80/books
            predicates:
            - Path=/orders/**
            filters:
            -  name: CircuitBreaker
               args:
                  name: orderCircuitBreaker
                  statusCodes:
                  - NOT_FOUND
                  - INTERNAL_SERVER_ERROR
            -  name: Retry
               args:
                  retries: 3
                  methods: GET
                  series: SERVER_ERROR
                  exceptions: java.net.ConnectException
                  backoff:
                     firstBackoff: 1s
                     maxBackOff: 10s
                     factor: 2
                     basedOnPreviousValue: false